[package]
name = "empkg"
version = "0.1.0"
authors = ["Johnson Zhang <johnson9009@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
